//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 01:24:22 AM BRT 
//


package com.ibm.stats;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageFlow">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="BrokerLabel" type="{}_String32" />
 *                 &lt;attribute name="BrokerUUID" type="{}_UUID" />
 *                 &lt;attribute name="ExecutionGroupName" type="{}_String32" />
 *                 &lt;attribute name="ExecutionGroupUUID" type="{}_UUID" />
 *                 &lt;attribute name="MessageFlowName" type="{}_String32" />
 *                 &lt;attribute name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                 &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}time" />
 *                 &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MaximumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MinimumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MaximumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MinimumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="CPUTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="ElapsedTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MaximumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="MinimumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="NumberOfThreadsInPool" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TimesMaximumNumberOfThreadsReached" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfMQErrors" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfMessagesWithErrors" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfErrorsProcessingMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfTimeOutsWaitingForRepliesToAggregateMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfCommits" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="TotalNumberOfBackouts" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="AccountingOrigin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Threads">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ThreadStatistics">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="TotalNumberOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="CPUTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="ElapsedTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="TotalSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MaximumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MinimumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Nodes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="NodeStatistics" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TerminalStatistics" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MaximumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MinimumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MaximumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="MinimumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="NumberOfInputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="NumberOfOutputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="RecordType" type="{}_RecordType" />
 *       &lt;attribute name="RecordCode" type="{}_RecordCode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageFlow",
    "threads",
    "nodes"
})
@XmlRootElement(name = "WMQIStatisticsAccounting")
public class WMQIStatisticsAccounting {

    @XmlElement(name = "MessageFlow", required = true)
    protected WMQIStatisticsAccounting.MessageFlow messageFlow;
    @XmlElement(name = "Threads", required = true)
    protected WMQIStatisticsAccounting.Threads threads;
    @XmlElement(name = "Nodes", required = true)
    protected WMQIStatisticsAccounting.Nodes nodes;
    @XmlAttribute(name = "RecordType")
    protected RecordType recordType;
    @XmlAttribute(name = "RecordCode")
    protected RecordCode recordCode;

    /**
     * Gets the value of the messageFlow property.
     * 
     * @return
     *     possible object is
     *     {@link WMQIStatisticsAccounting.MessageFlow }
     *     
     */
    public WMQIStatisticsAccounting.MessageFlow getMessageFlow() {
        return messageFlow;
    }

    /**
     * Sets the value of the messageFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link WMQIStatisticsAccounting.MessageFlow }
     *     
     */
    public void setMessageFlow(WMQIStatisticsAccounting.MessageFlow value) {
        this.messageFlow = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     * @return
     *     possible object is
     *     {@link WMQIStatisticsAccounting.Threads }
     *     
     */
    public WMQIStatisticsAccounting.Threads getThreads() {
        return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     * @param value
     *     allowed object is
     *     {@link WMQIStatisticsAccounting.Threads }
     *     
     */
    public void setThreads(WMQIStatisticsAccounting.Threads value) {
        this.threads = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link WMQIStatisticsAccounting.Nodes }
     *     
     */
    public WMQIStatisticsAccounting.Nodes getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link WMQIStatisticsAccounting.Nodes }
     *     
     */
    public void setNodes(WMQIStatisticsAccounting.Nodes value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link RecordType }
     *     
     */
    public RecordType getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordType }
     *     
     */
    public void setRecordType(RecordType value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the recordCode property.
     * 
     * @return
     *     possible object is
     *     {@link RecordCode }
     *     
     */
    public RecordCode getRecordCode() {
        return recordCode;
    }

    /**
     * Sets the value of the recordCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordCode }
     *     
     */
    public void setRecordCode(RecordCode value) {
        this.recordCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="BrokerLabel" type="{}_String32" />
     *       &lt;attribute name="BrokerUUID" type="{}_UUID" />
     *       &lt;attribute name="ExecutionGroupName" type="{}_String32" />
     *       &lt;attribute name="ExecutionGroupUUID" type="{}_UUID" />
     *       &lt;attribute name="MessageFlowName" type="{}_String32" />
     *       &lt;attribute name="ApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="StartTime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *       &lt;attribute name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="EndTime" type="{http://www.w3.org/2001/XMLSchema}time" />
     *       &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MaximumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MinimumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MaximumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MinimumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="CPUTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="ElapsedTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MaximumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="MinimumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="NumberOfThreadsInPool" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TimesMaximumNumberOfThreadsReached" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfMQErrors" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfMessagesWithErrors" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfErrorsProcessingMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfTimeOutsWaitingForRepliesToAggregateMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfCommits" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="TotalNumberOfBackouts" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="AccountingOrigin" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MessageFlow {

        @XmlAttribute(name = "BrokerLabel")
        protected String brokerLabel;
        @XmlAttribute(name = "BrokerUUID")
        protected String brokerUUID;
        @XmlAttribute(name = "ExecutionGroupName")
        protected String executionGroupName;
        @XmlAttribute(name = "ExecutionGroupUUID")
        protected String executionGroupUUID;
        @XmlAttribute(name = "MessageFlowName")
        protected String messageFlowName;
        @XmlAttribute(name = "ApplicationName")
        protected String applicationName;
        @XmlAttribute(name = "StartDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlAttribute(name = "StartTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar startTime;
        @XmlAttribute(name = "EndDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlAttribute(name = "EndTime")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar endTime;
        @XmlAttribute(name = "TotalElapsedTime")
        protected Long totalElapsedTime;
        @XmlAttribute(name = "MaximumElapsedTime")
        protected Long maximumElapsedTime;
        @XmlAttribute(name = "MinimumElapsedTime")
        protected Long minimumElapsedTime;
        @XmlAttribute(name = "TotalCPUTime")
        protected Long totalCPUTime;
        @XmlAttribute(name = "MaximumCPUTime")
        protected Long maximumCPUTime;
        @XmlAttribute(name = "MinimumCPUTime")
        protected Long minimumCPUTime;
        @XmlAttribute(name = "CPUTimeWaitingForInputMessage")
        protected Long cpuTimeWaitingForInputMessage;
        @XmlAttribute(name = "ElapsedTimeWaitingForInputMessage")
        protected Long elapsedTimeWaitingForInputMessage;
        @XmlAttribute(name = "TotalInputMessages")
        protected Long totalInputMessages;
        @XmlAttribute(name = "TotalSizeOfInputMessages")
        protected Long totalSizeOfInputMessages;
        @XmlAttribute(name = "MaximumSizeOfInputMessages")
        protected Long maximumSizeOfInputMessages;
        @XmlAttribute(name = "MinimumSizeOfInputMessages")
        protected Long minimumSizeOfInputMessages;
        @XmlAttribute(name = "NumberOfThreadsInPool")
        protected Long numberOfThreadsInPool;
        @XmlAttribute(name = "TimesMaximumNumberOfThreadsReached")
        protected Long timesMaximumNumberOfThreadsReached;
        @XmlAttribute(name = "TotalNumberOfMQErrors")
        protected Long totalNumberOfMQErrors;
        @XmlAttribute(name = "TotalNumberOfMessagesWithErrors")
        protected Long totalNumberOfMessagesWithErrors;
        @XmlAttribute(name = "TotalNumberOfErrorsProcessingMessages")
        protected Long totalNumberOfErrorsProcessingMessages;
        @XmlAttribute(name = "TotalNumberOfTimeOutsWaitingForRepliesToAggregateMessages")
        protected Long totalNumberOfTimeOutsWaitingForRepliesToAggregateMessages;
        @XmlAttribute(name = "TotalNumberOfCommits")
        protected Long totalNumberOfCommits;
        @XmlAttribute(name = "TotalNumberOfBackouts")
        protected Long totalNumberOfBackouts;
        @XmlAttribute(name = "AccountingOrigin")
        protected String accountingOrigin;

        /**
         * Gets the value of the brokerLabel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrokerLabel() {
            return brokerLabel;
        }

        /**
         * Sets the value of the brokerLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrokerLabel(String value) {
            this.brokerLabel = value;
        }

        /**
         * Gets the value of the brokerUUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrokerUUID() {
            return brokerUUID;
        }

        /**
         * Sets the value of the brokerUUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrokerUUID(String value) {
            this.brokerUUID = value;
        }

        /**
         * Gets the value of the executionGroupName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExecutionGroupName() {
            return executionGroupName;
        }

        /**
         * Sets the value of the executionGroupName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExecutionGroupName(String value) {
            this.executionGroupName = value;
        }

        /**
         * Gets the value of the executionGroupUUID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExecutionGroupUUID() {
            return executionGroupUUID;
        }

        /**
         * Sets the value of the executionGroupUUID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExecutionGroupUUID(String value) {
            this.executionGroupUUID = value;
        }

        /**
         * Gets the value of the messageFlowName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageFlowName() {
            return messageFlowName;
        }

        /**
         * Sets the value of the messageFlowName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageFlowName(String value) {
            this.messageFlowName = value;
        }

        /**
         * Gets the value of the applicationName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApplicationName() {
            return applicationName;
        }

        /**
         * Sets the value of the applicationName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApplicationName(String value) {
            this.applicationName = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the startTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartTime() {
            return startTime;
        }

        /**
         * Sets the value of the startTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartTime(XMLGregorianCalendar value) {
            this.startTime = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the endTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndTime() {
            return endTime;
        }

        /**
         * Sets the value of the endTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndTime(XMLGregorianCalendar value) {
            this.endTime = value;
        }

        /**
         * Gets the value of the totalElapsedTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalElapsedTime() {
            return totalElapsedTime;
        }

        /**
         * Sets the value of the totalElapsedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalElapsedTime(Long value) {
            this.totalElapsedTime = value;
        }

        /**
         * Gets the value of the maximumElapsedTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMaximumElapsedTime() {
            return maximumElapsedTime;
        }

        /**
         * Sets the value of the maximumElapsedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMaximumElapsedTime(Long value) {
            this.maximumElapsedTime = value;
        }

        /**
         * Gets the value of the minimumElapsedTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMinimumElapsedTime() {
            return minimumElapsedTime;
        }

        /**
         * Sets the value of the minimumElapsedTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMinimumElapsedTime(Long value) {
            this.minimumElapsedTime = value;
        }

        /**
         * Gets the value of the totalCPUTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalCPUTime() {
            return totalCPUTime;
        }

        /**
         * Sets the value of the totalCPUTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalCPUTime(Long value) {
            this.totalCPUTime = value;
        }

        /**
         * Gets the value of the maximumCPUTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMaximumCPUTime() {
            return maximumCPUTime;
        }

        /**
         * Sets the value of the maximumCPUTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMaximumCPUTime(Long value) {
            this.maximumCPUTime = value;
        }

        /**
         * Gets the value of the minimumCPUTime property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMinimumCPUTime() {
            return minimumCPUTime;
        }

        /**
         * Sets the value of the minimumCPUTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMinimumCPUTime(Long value) {
            this.minimumCPUTime = value;
        }

        /**
         * Gets the value of the cpuTimeWaitingForInputMessage property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getCPUTimeWaitingForInputMessage() {
            return cpuTimeWaitingForInputMessage;
        }

        /**
         * Sets the value of the cpuTimeWaitingForInputMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setCPUTimeWaitingForInputMessage(Long value) {
            this.cpuTimeWaitingForInputMessage = value;
        }

        /**
         * Gets the value of the elapsedTimeWaitingForInputMessage property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getElapsedTimeWaitingForInputMessage() {
            return elapsedTimeWaitingForInputMessage;
        }

        /**
         * Sets the value of the elapsedTimeWaitingForInputMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setElapsedTimeWaitingForInputMessage(Long value) {
            this.elapsedTimeWaitingForInputMessage = value;
        }

        /**
         * Gets the value of the totalInputMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalInputMessages() {
            return totalInputMessages;
        }

        /**
         * Sets the value of the totalInputMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalInputMessages(Long value) {
            this.totalInputMessages = value;
        }

        /**
         * Gets the value of the totalSizeOfInputMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalSizeOfInputMessages() {
            return totalSizeOfInputMessages;
        }

        /**
         * Sets the value of the totalSizeOfInputMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalSizeOfInputMessages(Long value) {
            this.totalSizeOfInputMessages = value;
        }

        /**
         * Gets the value of the maximumSizeOfInputMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMaximumSizeOfInputMessages() {
            return maximumSizeOfInputMessages;
        }

        /**
         * Sets the value of the maximumSizeOfInputMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMaximumSizeOfInputMessages(Long value) {
            this.maximumSizeOfInputMessages = value;
        }

        /**
         * Gets the value of the minimumSizeOfInputMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getMinimumSizeOfInputMessages() {
            return minimumSizeOfInputMessages;
        }

        /**
         * Sets the value of the minimumSizeOfInputMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setMinimumSizeOfInputMessages(Long value) {
            this.minimumSizeOfInputMessages = value;
        }

        /**
         * Gets the value of the numberOfThreadsInPool property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getNumberOfThreadsInPool() {
            return numberOfThreadsInPool;
        }

        /**
         * Sets the value of the numberOfThreadsInPool property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setNumberOfThreadsInPool(Long value) {
            this.numberOfThreadsInPool = value;
        }

        /**
         * Gets the value of the timesMaximumNumberOfThreadsReached property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTimesMaximumNumberOfThreadsReached() {
            return timesMaximumNumberOfThreadsReached;
        }

        /**
         * Sets the value of the timesMaximumNumberOfThreadsReached property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTimesMaximumNumberOfThreadsReached(Long value) {
            this.timesMaximumNumberOfThreadsReached = value;
        }

        /**
         * Gets the value of the totalNumberOfMQErrors property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfMQErrors() {
            return totalNumberOfMQErrors;
        }

        /**
         * Sets the value of the totalNumberOfMQErrors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfMQErrors(Long value) {
            this.totalNumberOfMQErrors = value;
        }

        /**
         * Gets the value of the totalNumberOfMessagesWithErrors property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfMessagesWithErrors() {
            return totalNumberOfMessagesWithErrors;
        }

        /**
         * Sets the value of the totalNumberOfMessagesWithErrors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfMessagesWithErrors(Long value) {
            this.totalNumberOfMessagesWithErrors = value;
        }

        /**
         * Gets the value of the totalNumberOfErrorsProcessingMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfErrorsProcessingMessages() {
            return totalNumberOfErrorsProcessingMessages;
        }

        /**
         * Sets the value of the totalNumberOfErrorsProcessingMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfErrorsProcessingMessages(Long value) {
            this.totalNumberOfErrorsProcessingMessages = value;
        }

        /**
         * Gets the value of the totalNumberOfTimeOutsWaitingForRepliesToAggregateMessages property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfTimeOutsWaitingForRepliesToAggregateMessages() {
            return totalNumberOfTimeOutsWaitingForRepliesToAggregateMessages;
        }

        /**
         * Sets the value of the totalNumberOfTimeOutsWaitingForRepliesToAggregateMessages property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfTimeOutsWaitingForRepliesToAggregateMessages(Long value) {
            this.totalNumberOfTimeOutsWaitingForRepliesToAggregateMessages = value;
        }

        /**
         * Gets the value of the totalNumberOfCommits property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfCommits() {
            return totalNumberOfCommits;
        }

        /**
         * Sets the value of the totalNumberOfCommits property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfCommits(Long value) {
            this.totalNumberOfCommits = value;
        }

        /**
         * Gets the value of the totalNumberOfBackouts property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getTotalNumberOfBackouts() {
            return totalNumberOfBackouts;
        }

        /**
         * Sets the value of the totalNumberOfBackouts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setTotalNumberOfBackouts(Long value) {
            this.totalNumberOfBackouts = value;
        }

        /**
         * Gets the value of the accountingOrigin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountingOrigin() {
            return accountingOrigin;
        }

        /**
         * Sets the value of the accountingOrigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountingOrigin(String value) {
            this.accountingOrigin = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="NodeStatistics" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TerminalStatistics" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MaximumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MinimumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MaximumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MinimumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="NumberOfInputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="NumberOfOutputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nodeStatistics"
    })
    public static class Nodes {

        @XmlElement(name = "NodeStatistics")
        protected List<WMQIStatisticsAccounting.Nodes.NodeStatistics> nodeStatistics;
        @XmlAttribute(name = "Number")
        protected Integer number;

        /**
         * Gets the value of the nodeStatistics property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nodeStatistics property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNodeStatistics().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WMQIStatisticsAccounting.Nodes.NodeStatistics }
         * 
         * 
         */
        public List<WMQIStatisticsAccounting.Nodes.NodeStatistics> getNodeStatistics() {
            if (nodeStatistics == null) {
                nodeStatistics = new ArrayList<WMQIStatisticsAccounting.Nodes.NodeStatistics>();
            }
            return this.nodeStatistics;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumber(Integer value) {
            this.number = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TerminalStatistics" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MaximumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MinimumElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MaximumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MinimumCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="NumberOfInputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="NumberOfOutputTerminals" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "terminalStatistics"
        })
        public static class NodeStatistics {

            @XmlElement(name = "TerminalStatistics")
            protected List<WMQIStatisticsAccounting.Nodes.NodeStatistics.TerminalStatistics> terminalStatistics;
            @XmlAttribute(name = "Label")
            protected String label;
            @XmlAttribute(name = "Type")
            protected String type;
            @XmlAttribute(name = "TotalElapsedTime")
            protected Long totalElapsedTime;
            @XmlAttribute(name = "MaximumElapsedTime")
            protected Long maximumElapsedTime;
            @XmlAttribute(name = "MinimumElapsedTime")
            protected Long minimumElapsedTime;
            @XmlAttribute(name = "TotalCPUTime")
            protected Long totalCPUTime;
            @XmlAttribute(name = "MaximumCPUTime")
            protected Long maximumCPUTime;
            @XmlAttribute(name = "MinimumCPUTime")
            protected Long minimumCPUTime;
            @XmlAttribute(name = "CountOfInvocations")
            protected Long countOfInvocations;
            @XmlAttribute(name = "NumberOfInputTerminals")
            protected Long numberOfInputTerminals;
            @XmlAttribute(name = "NumberOfOutputTerminals")
            protected Long numberOfOutputTerminals;

            /**
             * Gets the value of the terminalStatistics property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the terminalStatistics property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTerminalStatistics().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link WMQIStatisticsAccounting.Nodes.NodeStatistics.TerminalStatistics }
             * 
             * 
             */
            public List<WMQIStatisticsAccounting.Nodes.NodeStatistics.TerminalStatistics> getTerminalStatistics() {
                if (terminalStatistics == null) {
                    terminalStatistics = new ArrayList<WMQIStatisticsAccounting.Nodes.NodeStatistics.TerminalStatistics>();
                }
                return this.terminalStatistics;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the totalElapsedTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalElapsedTime() {
                return totalElapsedTime;
            }

            /**
             * Sets the value of the totalElapsedTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalElapsedTime(Long value) {
                this.totalElapsedTime = value;
            }

            /**
             * Gets the value of the maximumElapsedTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMaximumElapsedTime() {
                return maximumElapsedTime;
            }

            /**
             * Sets the value of the maximumElapsedTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMaximumElapsedTime(Long value) {
                this.maximumElapsedTime = value;
            }

            /**
             * Gets the value of the minimumElapsedTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMinimumElapsedTime() {
                return minimumElapsedTime;
            }

            /**
             * Sets the value of the minimumElapsedTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMinimumElapsedTime(Long value) {
                this.minimumElapsedTime = value;
            }

            /**
             * Gets the value of the totalCPUTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalCPUTime() {
                return totalCPUTime;
            }

            /**
             * Sets the value of the totalCPUTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalCPUTime(Long value) {
                this.totalCPUTime = value;
            }

            /**
             * Gets the value of the maximumCPUTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMaximumCPUTime() {
                return maximumCPUTime;
            }

            /**
             * Sets the value of the maximumCPUTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMaximumCPUTime(Long value) {
                this.maximumCPUTime = value;
            }

            /**
             * Gets the value of the minimumCPUTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMinimumCPUTime() {
                return minimumCPUTime;
            }

            /**
             * Sets the value of the minimumCPUTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMinimumCPUTime(Long value) {
                this.minimumCPUTime = value;
            }

            /**
             * Gets the value of the countOfInvocations property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getCountOfInvocations() {
                return countOfInvocations;
            }

            /**
             * Sets the value of the countOfInvocations property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCountOfInvocations(Long value) {
                this.countOfInvocations = value;
            }

            /**
             * Gets the value of the numberOfInputTerminals property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getNumberOfInputTerminals() {
                return numberOfInputTerminals;
            }

            /**
             * Sets the value of the numberOfInputTerminals property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setNumberOfInputTerminals(Long value) {
                this.numberOfInputTerminals = value;
            }

            /**
             * Gets the value of the numberOfOutputTerminals property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getNumberOfOutputTerminals() {
                return numberOfOutputTerminals;
            }

            /**
             * Sets the value of the numberOfOutputTerminals property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setNumberOfOutputTerminals(Long value) {
                this.numberOfOutputTerminals = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Label" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="CountOfInvocations" type="{http://www.w3.org/2001/XMLSchema}long" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class TerminalStatistics {

                @XmlAttribute(name = "Label")
                protected String label;
                @XmlAttribute(name = "Type")
                protected String type;
                @XmlAttribute(name = "CountOfInvocations")
                protected Long countOfInvocations;

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the countOfInvocations property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Long }
                 *     
                 */
                public Long getCountOfInvocations() {
                    return countOfInvocations;
                }

                /**
                 * Sets the value of the countOfInvocations property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Long }
                 *     
                 */
                public void setCountOfInvocations(Long value) {
                    this.countOfInvocations = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ThreadStatistics">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="TotalNumberOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="CPUTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="ElapsedTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="TotalSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MaximumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="MinimumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "threadStatistics"
    })
    public static class Threads {

        @XmlElement(name = "ThreadStatistics", required = true)
        protected WMQIStatisticsAccounting.Threads.ThreadStatistics threadStatistics;
        @XmlAttribute(name = "Number")
        protected Integer number;

        /**
         * Gets the value of the threadStatistics property.
         * 
         * @return
         *     possible object is
         *     {@link WMQIStatisticsAccounting.Threads.ThreadStatistics }
         *     
         */
        public WMQIStatisticsAccounting.Threads.ThreadStatistics getThreadStatistics() {
            return threadStatistics;
        }

        /**
         * Sets the value of the threadStatistics property.
         * 
         * @param value
         *     allowed object is
         *     {@link WMQIStatisticsAccounting.Threads.ThreadStatistics }
         *     
         */
        public void setThreadStatistics(WMQIStatisticsAccounting.Threads.ThreadStatistics value) {
            this.threadStatistics = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumber(Integer value) {
            this.number = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Number" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="TotalNumberOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="TotalElapsedTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="TotalCPUTime" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="CPUTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="ElapsedTimeWaitingForInputMessage" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="TotalSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MaximumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="MinimumSizeOfInputMessages" type="{http://www.w3.org/2001/XMLSchema}long" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ThreadStatistics {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Number")
            protected Integer number;
            @XmlAttribute(name = "TotalNumberOfInputMessages")
            protected Long totalNumberOfInputMessages;
            @XmlAttribute(name = "TotalElapsedTime")
            protected Long totalElapsedTime;
            @XmlAttribute(name = "TotalCPUTime")
            protected Long totalCPUTime;
            @XmlAttribute(name = "CPUTimeWaitingForInputMessage")
            protected Long cpuTimeWaitingForInputMessage;
            @XmlAttribute(name = "ElapsedTimeWaitingForInputMessage")
            protected Long elapsedTimeWaitingForInputMessage;
            @XmlAttribute(name = "TotalSizeOfInputMessages")
            protected Long totalSizeOfInputMessages;
            @XmlAttribute(name = "MaximumSizeOfInputMessages")
            protected Long maximumSizeOfInputMessages;
            @XmlAttribute(name = "MinimumSizeOfInputMessages")
            protected Long minimumSizeOfInputMessages;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNumber(Integer value) {
                this.number = value;
            }

            /**
             * Gets the value of the totalNumberOfInputMessages property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalNumberOfInputMessages() {
                return totalNumberOfInputMessages;
            }

            /**
             * Sets the value of the totalNumberOfInputMessages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalNumberOfInputMessages(Long value) {
                this.totalNumberOfInputMessages = value;
            }

            /**
             * Gets the value of the totalElapsedTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalElapsedTime() {
                return totalElapsedTime;
            }

            /**
             * Sets the value of the totalElapsedTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalElapsedTime(Long value) {
                this.totalElapsedTime = value;
            }

            /**
             * Gets the value of the totalCPUTime property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalCPUTime() {
                return totalCPUTime;
            }

            /**
             * Sets the value of the totalCPUTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalCPUTime(Long value) {
                this.totalCPUTime = value;
            }

            /**
             * Gets the value of the cpuTimeWaitingForInputMessage property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getCPUTimeWaitingForInputMessage() {
                return cpuTimeWaitingForInputMessage;
            }

            /**
             * Sets the value of the cpuTimeWaitingForInputMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setCPUTimeWaitingForInputMessage(Long value) {
                this.cpuTimeWaitingForInputMessage = value;
            }

            /**
             * Gets the value of the elapsedTimeWaitingForInputMessage property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getElapsedTimeWaitingForInputMessage() {
                return elapsedTimeWaitingForInputMessage;
            }

            /**
             * Sets the value of the elapsedTimeWaitingForInputMessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setElapsedTimeWaitingForInputMessage(Long value) {
                this.elapsedTimeWaitingForInputMessage = value;
            }

            /**
             * Gets the value of the totalSizeOfInputMessages property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getTotalSizeOfInputMessages() {
                return totalSizeOfInputMessages;
            }

            /**
             * Sets the value of the totalSizeOfInputMessages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setTotalSizeOfInputMessages(Long value) {
                this.totalSizeOfInputMessages = value;
            }

            /**
             * Gets the value of the maximumSizeOfInputMessages property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMaximumSizeOfInputMessages() {
                return maximumSizeOfInputMessages;
            }

            /**
             * Sets the value of the maximumSizeOfInputMessages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMaximumSizeOfInputMessages(Long value) {
                this.maximumSizeOfInputMessages = value;
            }

            /**
             * Gets the value of the minimumSizeOfInputMessages property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMinimumSizeOfInputMessages() {
                return minimumSizeOfInputMessages;
            }

            /**
             * Sets the value of the minimumSizeOfInputMessages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMinimumSizeOfInputMessages(Long value) {
                this.minimumSizeOfInputMessages = value;
            }

        }

    }

}
