//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 03:57:48 PM BRST 
//


package com.ibm.wmb.monitor.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EventPointData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventPointData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="eventIdentity">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="eventName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="successDisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="eventSequence">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="creationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="counter" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="dataType" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}sequenceDataType" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="eventCorrelation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="localTransactionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="parentTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="globalTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="productVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="eventSchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="eventSourceAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="messageFlowData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broker">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="executionGroup">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="messageFlow">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="threadId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="uniqueFlowName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="node">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="nodeLabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nodeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="detail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventPointData", propOrder = {
    "eventData",
    "messageFlowData"
})
public class EventPointData {

    @XmlElement(required = true)
    protected EventPointData.EventData eventData;
    @XmlElement(required = true)
    protected EventPointData.MessageFlowData messageFlowData;

    /**
     * Gets the value of the eventData property.
     * 
     * @return
     *     possible object is
     *     {@link EventPointData.EventData }
     *     
     */
    public EventPointData.EventData getEventData() {
        return eventData;
    }

    /**
     * Sets the value of the eventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPointData.EventData }
     *     
     */
    public void setEventData(EventPointData.EventData value) {
        this.eventData = value;
    }

    /**
     * Gets the value of the messageFlowData property.
     * 
     * @return
     *     possible object is
     *     {@link EventPointData.MessageFlowData }
     *     
     */
    public EventPointData.MessageFlowData getMessageFlowData() {
        return messageFlowData;
    }

    /**
     * Sets the value of the messageFlowData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPointData.MessageFlowData }
     *     
     */
    public void setMessageFlowData(EventPointData.MessageFlowData value) {
        this.messageFlowData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="eventIdentity">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="eventName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="successDisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="eventSequence">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="creationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="counter" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="dataType" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}sequenceDataType" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="eventCorrelation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="localTransactionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="parentTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="globalTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="productVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="eventSchemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="eventSourceAddress" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eventIdentity",
        "eventSequence",
        "eventCorrelation"
    })
    public static class EventData {

        @XmlElement(required = true)
        protected EventPointData.EventData.EventIdentity eventIdentity;
        @XmlElement(required = true)
        protected EventPointData.EventData.EventSequence eventSequence;
        @XmlElement(required = true)
        protected EventPointData.EventData.EventCorrelation eventCorrelation;
        @XmlAttribute(name = "productVersion", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
        protected String productVersion;
        @XmlAttribute(name = "eventSchemaVersion", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
        protected String eventSchemaVersion;
        @XmlAttribute(name = "eventSourceAddress", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
        protected String eventSourceAddress;

        /**
         * Gets the value of the eventIdentity property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.EventData.EventIdentity }
         *     
         */
        public EventPointData.EventData.EventIdentity getEventIdentity() {
            return eventIdentity;
        }

        /**
         * Sets the value of the eventIdentity property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.EventData.EventIdentity }
         *     
         */
        public void setEventIdentity(EventPointData.EventData.EventIdentity value) {
            this.eventIdentity = value;
        }

        /**
         * Gets the value of the eventSequence property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.EventData.EventSequence }
         *     
         */
        public EventPointData.EventData.EventSequence getEventSequence() {
            return eventSequence;
        }

        /**
         * Sets the value of the eventSequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.EventData.EventSequence }
         *     
         */
        public void setEventSequence(EventPointData.EventData.EventSequence value) {
            this.eventSequence = value;
        }

        /**
         * Gets the value of the eventCorrelation property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.EventData.EventCorrelation }
         *     
         */
        public EventPointData.EventData.EventCorrelation getEventCorrelation() {
            return eventCorrelation;
        }

        /**
         * Sets the value of the eventCorrelation property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.EventData.EventCorrelation }
         *     
         */
        public void setEventCorrelation(EventPointData.EventData.EventCorrelation value) {
            this.eventCorrelation = value;
        }

        /**
         * Gets the value of the productVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductVersion() {
            return productVersion;
        }

        /**
         * Sets the value of the productVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductVersion(String value) {
            this.productVersion = value;
        }

        /**
         * Gets the value of the eventSchemaVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventSchemaVersion() {
            return eventSchemaVersion;
        }

        /**
         * Sets the value of the eventSchemaVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventSchemaVersion(String value) {
            this.eventSchemaVersion = value;
        }

        /**
         * Gets the value of the eventSourceAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEventSourceAddress() {
            return eventSourceAddress;
        }

        /**
         * Sets the value of the eventSourceAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEventSourceAddress(String value) {
            this.eventSourceAddress = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="localTransactionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="parentTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="globalTransactionId" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EventCorrelation {

            @XmlAttribute(name = "localTransactionId", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String localTransactionId;
            @XmlAttribute(name = "parentTransactionId", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String parentTransactionId;
            @XmlAttribute(name = "globalTransactionId", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String globalTransactionId;

            /**
             * Gets the value of the localTransactionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocalTransactionId() {
                return localTransactionId;
            }

            /**
             * Sets the value of the localTransactionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocalTransactionId(String value) {
                this.localTransactionId = value;
            }

            /**
             * Gets the value of the parentTransactionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getParentTransactionId() {
                return parentTransactionId;
            }

            /**
             * Sets the value of the parentTransactionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setParentTransactionId(String value) {
                this.parentTransactionId = value;
            }

            /**
             * Gets the value of the globalTransactionId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGlobalTransactionId() {
                return globalTransactionId;
            }

            /**
             * Sets the value of the globalTransactionId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGlobalTransactionId(String value) {
                this.globalTransactionId = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="eventName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="successDisposition" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EventIdentity {

            @XmlAttribute(name = "eventName", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String eventName;
            @XmlAttribute(name = "severity", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String severity;
            @XmlAttribute(name = "priority", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String priority;
            @XmlAttribute(name = "successDisposition", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String successDisposition;

            /**
             * Gets the value of the eventName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEventName() {
                return eventName;
            }

            /**
             * Sets the value of the eventName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEventName(String value) {
                this.eventName = value;
            }

            /**
             * Gets the value of the severity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeverity() {
                return severity;
            }

            /**
             * Sets the value of the severity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeverity(String value) {
                this.severity = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriority(String value) {
                this.priority = value;
            }

            /**
             * Gets the value of the successDisposition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSuccessDisposition() {
                return successDisposition;
            }

            /**
             * Sets the value of the successDisposition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSuccessDisposition(String value) {
                this.successDisposition = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="creationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="counter" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="dataType" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}sequenceDataType" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EventSequence {

            @XmlAttribute(name = "creationTime", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creationTime;
            @XmlAttribute(name = "counter", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected BigInteger counter;
            @XmlAttribute(name = "value", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            @XmlSchemaType(name = "anySimpleType")
            protected String value;
            @XmlAttribute(name = "name", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String name;
            @XmlAttribute(name = "dataType", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected SequenceDataType dataType;

            /**
             * Gets the value of the creationTime property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreationTime() {
                return creationTime;
            }

            /**
             * Sets the value of the creationTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreationTime(XMLGregorianCalendar value) {
                this.creationTime = value;
            }

            /**
             * Gets the value of the counter property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCounter() {
                return counter;
            }

            /**
             * Sets the value of the counter property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCounter(BigInteger value) {
                this.counter = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link SequenceDataType }
             *     
             */
            public SequenceDataType getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link SequenceDataType }
             *     
             */
            public void setDataType(SequenceDataType value) {
                this.dataType = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broker">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="executionGroup">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="messageFlow">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="threadId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="uniqueFlowName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="node">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="nodeLabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="nodeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="detail" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "broker",
        "executionGroup",
        "messageFlow",
        "node"
    })
    public static class MessageFlowData {

        @XmlElement(required = true)
        protected EventPointData.MessageFlowData.Broker broker;
        @XmlElement(required = true)
        protected EventPointData.MessageFlowData.ExecutionGroup executionGroup;
        @XmlElement(required = true)
        protected EventPointData.MessageFlowData.MessageFlow messageFlow;
        @XmlElement(required = true)
        protected EventPointData.MessageFlowData.Node node;

        /**
         * Gets the value of the broker property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.MessageFlowData.Broker }
         *     
         */
        public EventPointData.MessageFlowData.Broker getBroker() {
            return broker;
        }

        /**
         * Sets the value of the broker property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.MessageFlowData.Broker }
         *     
         */
        public void setBroker(EventPointData.MessageFlowData.Broker value) {
            this.broker = value;
        }

        /**
         * Gets the value of the executionGroup property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.MessageFlowData.ExecutionGroup }
         *     
         */
        public EventPointData.MessageFlowData.ExecutionGroup getExecutionGroup() {
            return executionGroup;
        }

        /**
         * Sets the value of the executionGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.MessageFlowData.ExecutionGroup }
         *     
         */
        public void setExecutionGroup(EventPointData.MessageFlowData.ExecutionGroup value) {
            this.executionGroup = value;
        }

        /**
         * Gets the value of the messageFlow property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.MessageFlowData.MessageFlow }
         *     
         */
        public EventPointData.MessageFlowData.MessageFlow getMessageFlow() {
            return messageFlow;
        }

        /**
         * Sets the value of the messageFlow property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.MessageFlowData.MessageFlow }
         *     
         */
        public void setMessageFlow(EventPointData.MessageFlowData.MessageFlow value) {
            this.messageFlow = value;
        }

        /**
         * Gets the value of the node property.
         * 
         * @return
         *     possible object is
         *     {@link EventPointData.MessageFlowData.Node }
         *     
         */
        public EventPointData.MessageFlowData.Node getNode() {
            return node;
        }

        /**
         * Sets the value of the node property.
         * 
         * @param value
         *     allowed object is
         *     {@link EventPointData.MessageFlowData.Node }
         *     
         */
        public void setNode(EventPointData.MessageFlowData.Node value) {
            this.node = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hostName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Broker {

            @XmlAttribute(name = "name", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String name;
            @XmlAttribute(name = "UUID", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String uuid;
            @XmlAttribute(name = "hostName", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String hostName;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUUID() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUUID(String value) {
                this.uuid = value;
            }

            /**
             * Gets the value of the hostName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostName() {
                return hostName;
            }

            /**
             * Sets the value of the hostName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostName(String value) {
                this.hostName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ExecutionGroup {

            @XmlAttribute(name = "name", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String name;
            @XmlAttribute(name = "UUID", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String uuid;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUUID() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUUID(String value) {
                this.uuid = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="threadId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="uniqueFlowName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class MessageFlow {

            @XmlAttribute(name = "name", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String name;
            @XmlAttribute(name = "UUID", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String uuid;
            @XmlAttribute(name = "threadId", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String threadId;
            @XmlAttribute(name = "uniqueFlowName", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String uniqueFlowName;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUUID() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUUID(String value) {
                this.uuid = value;
            }

            /**
             * Gets the value of the threadId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getThreadId() {
                return threadId;
            }

            /**
             * Sets the value of the threadId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setThreadId(String value) {
                this.threadId = value;
            }

            /**
             * Gets the value of the uniqueFlowName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUniqueFlowName() {
                return uniqueFlowName;
            }

            /**
             * Sets the value of the uniqueFlowName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUniqueFlowName(String value) {
                this.uniqueFlowName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="nodeLabel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="nodeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="terminal" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="detail" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Node {

            @XmlAttribute(name = "nodeLabel", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String nodeLabel;
            @XmlAttribute(name = "nodeType", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event", required = true)
            protected String nodeType;
            @XmlAttribute(name = "terminal", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String terminal;
            @XmlAttribute(name = "detail", namespace = "http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event")
            protected String detail;

            /**
             * Gets the value of the nodeLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeLabel() {
                return nodeLabel;
            }

            /**
             * Sets the value of the nodeLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeLabel(String value) {
                this.nodeLabel = value;
            }

            /**
             * Gets the value of the nodeType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNodeType() {
                return nodeType;
            }

            /**
             * Sets the value of the nodeType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNodeType(String value) {
                this.nodeType = value;
            }

            /**
             * Gets the value of the terminal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTerminal() {
                return terminal;
            }

            /**
             * Sets the value of the terminal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTerminal(String value) {
                this.terminal = value;
            }

            /**
             * Gets the value of the detail property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetail() {
                return detail;
            }

            /**
             * Sets the value of the detail property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetail(String value) {
                this.detail = value;
            }

        }

    }

}
