//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.18 at 03:57:48 PM BRST 
//


package com.ibm.wmb.monitor.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Event complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Event">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventPointData" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}EventPointData"/>
 *         &lt;element name="applicationData" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}ApplicationData" minOccurs="0"/>
 *         &lt;element name="bitstreamData" type="{http://www.ibm.com/xmlns/prod/websphere/messagebroker/6.1.0/monitoring/event}BitstreamData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Event", propOrder = {
    "eventPointData",
    "applicationData",
    "bitstreamData"
})
public class Event {

    @XmlElement(required = true)
    protected EventPointData eventPointData;
    protected ApplicationData applicationData;
    protected BitstreamData bitstreamData;

    /**
     * Gets the value of the eventPointData property.
     * 
     * @return
     *     possible object is
     *     {@link EventPointData }
     *     
     */
    public EventPointData getEventPointData() {
        return eventPointData;
    }

    /**
     * Sets the value of the eventPointData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventPointData }
     *     
     */
    public void setEventPointData(EventPointData value) {
        this.eventPointData = value;
    }

    /**
     * Gets the value of the applicationData property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationData }
     *     
     */
    public ApplicationData getApplicationData() {
        return applicationData;
    }

    /**
     * Sets the value of the applicationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationData }
     *     
     */
    public void setApplicationData(ApplicationData value) {
        this.applicationData = value;
    }

    /**
     * Gets the value of the bitstreamData property.
     * 
     * @return
     *     possible object is
     *     {@link BitstreamData }
     *     
     */
    public BitstreamData getBitstreamData() {
        return bitstreamData;
    }

    /**
     * Sets the value of the bitstreamData property.
     * 
     * @param value
     *     allowed object is
     *     {@link BitstreamData }
     *     
     */
    public void setBitstreamData(BitstreamData value) {
        this.bitstreamData = value;
    }

}
